# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7ebb2a505381b9377cf44bd9d472cfd0cc8ae0b799bbcea0368436e89b7f581bb108e38aad7f2c84dc61f3d0178777a895d0b81fa3905aa9aefeb8d02cbb6cf

test:
  secret_key_base: 681fb6228a96c00c1290bf31424326bf71d916445cb9d0734b0e3d99f7d025d76abb51cac4706cafc9561567849102a93fe9529ab2e2e5db6d6c15cc26036edf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
